apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-client
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-client
  template:
    metadata:
      labels:
        app: api-client
    spec:
      nodeSelector:
        kubernetes.io/hostname: r3-node
      containers:
      - name: client-container
        image: ghcr.io/marcolo-30/k8s-gitops-lab:5082fbf58fac0adfd9476b4d12eabffaf871626d
        imagePullPolicy: Always
        # Assuming WORKDIR is /app, this will execute /app/client.py
        command: ["python", "client.py"]
        env:
        - name: SERVICE_ENDPOINT
          value: "http://image-processor-svc:8080"
        - name: SERVICE_NAME
          value: "api-client"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.observability.svc.cluster.local:4318"
