apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-app
  template:
    metadata:
      labels:
        app: main-app
    spec:
      containers:
        - name: main-app
          image: ghcr.io/marcolo-30/k8s-gitops-lab:65feed7a1e0a19d89cb55d92b5b4968c6f5f736c
          imagePullPolicy: Always
          env:
            - name: SERVICE_NAME
              value: "main-app"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://10.43.138.250:4318"
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "300m"
              memory: "64Mi"