apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-app
  template:
    metadata:
      labels:
        app: main-app
    spec:
      nodeSelector:
        kubernetes.io/hostname: r3-node # Make sure this is the correct node
      containers:
        - name: main-app
          # IMPORTANT: You will need to build and push a new image with the updated main.py
<<<<<<< Updated upstream
          image: ghcr.io/marcolo-30/k8s-gitops-lab:00f1a82c018e8e5163ef4373785b520618c8f2cb
=======
          image: ghcr.io/marcolo-30/k8s-gitops-lab:00f1a82c018e8e5163ef4373785b520618c8f2cb
>>>>>>> Stashed changes
          imagePullPolicy: Always
          env:
            - name: SERVICE_NAME
              value: "main-app"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://10.43.138.250:4318"
            - name: WORKLOAD_SIZE
              value: "200000"
            - name: NUM_WORKERS
              # Using 3 out of 4 cores to target ~75-80% CPU usage
              value: "2"
          resources:
            # This pod is 'Burstable'. It is guaranteed 100m of CPU.
            requests:
              cpu: "100m"
              memory: "128Mi" # Increased memory for multiple processes
            # By NOT setting a CPU limit, it can use all available cores
            # and be throttled by other high-priority pods.
